enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.1.cjs

npmScopes:
  "funcpp":
    npmAlwaysAuth: true
    npmAuthToken: "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"
    npmRegistryServer: "https://npm.pkg.github.com"
