enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.1.cjs

npmScopes:
  "funcpp":
    npmAlwaysAuth: true
    npmAuthToken: "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"
    npmRegistryServer: "https://npm.pkg.github.com"
